export const GET_ALL_CATEGORIES_REQUESTED = 'GET_ALL_CATEGORIES_REQUESTED';
export const GET_ALL_CATEGORIES_SUCCEEDED = 'GET_ALL_CATEGORIES_SUCCEEDED';
export const GET_ALL_CATEGORIES_FAILED = 'GET_ALL_CATEGORIES_FAILED';
export const GET_CAT_IMAGES_REQUESTED = 'GET_CAT_IMAGES_REQUESTED';
export const GET_CAT_IMAGES_SUCCEEDED = 'GET_CAT_IMAGES_SUCCEEDED';
export const GET_CAT_IMAGES_FAILED = 'GET_CAT_IMAGES_FAILED';