export const GET_ALL_CATEGORIES_REQUESTED = 'GET_ALL_CATEGORIES_REQUESTED';
export const GET_ALL_CATEGORIES_SUCCEEDED = 'GET_ALL_CATEGORIES_SUCCEEDED';
export const GET_ALL_CATEGORIES_FAILED = 'GET_ALL_CATEGORIES_FAILED';
export const GET_THE_CATEGORY_REQUESTED = 'GET_THE_CATEGORY_REQUESTED';
export const GET_THE_CATEGORY_SUCCEEDED = 'GET_THE_CATEGORY_SUCCEEDED';
export const GET_THE_CATEGORY_FAILED = 'GET_THE_CATEGORY_FAILED';